[hyprwinwrap]
description = "A soft fork of hyprwinwrap for Hyprland"
version = "1.0"
authors = ["keircn"]

[hyprwinwrap.build]
output = "hyprwinwrap/hyprwinwrap.so"
steps = ["make -C hyprwinwrap all"]
